### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by jpoeppelman1** [JordanMartin/harmonyhub-api#3]
I created a test file to connect to my hub using my IP and hub ID.

I get the following message.  Should there be a require command at the top of the file?

C:\Users\James\node_modules\test.js:5
const hub = new HarmonyHub(HUB_HOST, HUB_REMOTE_ID);
            ^

ReferenceError: HarmonyHub is not defined
    at Object.<anonymous> (C:\Users\James\node_modules\test.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

Here is the content of the file.

const HUB_HOST = '192.168.1.110';
const HUB_REMOTE_ID = '400.1';
const hub = new HarmonyHub(HUB_HOST, HUB_REMOTE_ID);

hub.connect()
    .then((config) => {
        console.log('Connected to the hub');

        console.log('\nActivities\n==========');
        config.activity.forEach(activity => {
            console.log(`${activity.label} (${activity.id})`);
        });

        console.log('\nDevices\n========');
        config.device.forEach(device => {
            console.log(`${device.label} (${device.id})`);
        });
    });

**Comment by JordanMartin** [comment]
You are missing the require/import statement : 
`const HarmonyHub = require('harmonyhub-api').HarmonyHub;`
